# Generated by Django 3.0 on 2020-08-13 04:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AmpuMatkul',
            fields=[
                ('kd_ampu', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('semester', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2)])),
                ('created_at', models.CharField(max_length=20)),
                ('updated_at', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('nip', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('created_at', models.CharField(max_length=20)),
                ('updated_at', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('kd_kelas', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('kelas', models.CharField(max_length=60)),
                ('created_at', models.CharField(max_length=20)),
                ('updated_at', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('nim', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('jurusan', models.CharField(max_length=50)),
                ('prodi', models.CharField(max_length=50)),
                ('created_at', models.CharField(max_length=20)),
                ('updated_at', models.CharField(max_length=20)),
                ('kd_kelas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.Kelas')),
            ],
        ),
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('kd_mk', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mata_kuliah', models.CharField(max_length=50)),
                ('sks', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2)])),
                ('created_at', models.CharField(max_length=20)),
                ('updated_at', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('kd_soal', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('judul_soal', models.CharField(max_length=255)),
                ('created_at', models.CharField(max_length=20)),
                ('updated_at', models.CharField(max_length=20)),
                ('kd_ampu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.AmpuMatkul')),
            ],
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('kd_nilai', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nilai', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('index', models.CharField(max_length=2)),
                ('created_at', models.CharField(max_length=20)),
                ('updated_at', models.CharField(max_length=20)),
                ('kd_soal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.Soal')),
                ('nim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.Mahasiswa')),
            ],
        ),
        migrations.CreateModel(
            name='LogNilai',
            fields=[
                ('kd_log', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('no', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('pertanyaan', models.TextField()),
                ('jawaban', models.TextField()),
                ('skor1', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('skor2', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('skor3', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('skor_akhir', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('created_at', models.CharField(max_length=20)),
                ('updated_at', models.CharField(max_length=20)),
                ('kd_nilai', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.Nilai')),
            ],
        ),
        migrations.CreateModel(
            name='DetailSoal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('soal', models.TextField()),
                ('jawaban1', models.TextField()),
                ('jawaban2', models.TextField()),
                ('jawaban3', models.TextField()),
                ('created_at', models.CharField(max_length=20)),
                ('updated_at', models.CharField(max_length=20)),
                ('kd_soal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.Soal')),
            ],
        ),
        migrations.AddField(
            model_name='ampumatkul',
            name='kd_kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.Kelas'),
        ),
        migrations.AddField(
            model_name='ampumatkul',
            name='kd_mk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.MataKuliah'),
        ),
        migrations.AddField(
            model_name='ampumatkul',
            name='nip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.Dosen'),
        ),
    ]
