# Generated by Django 3.0 on 2020-03-10 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmpuMatkul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_ampu', models.CharField(max_length=10)),
                ('semester', models.IntegerField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailSoal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('soal', models.TextField()),
                ('jawaban', models.TextField()),
                ('bobot', models.IntegerField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=18)),
                ('nama', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_kelas', models.CharField(max_length=10)),
                ('kelas', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_mk', models.CharField(max_length=10)),
                ('mata_kuliah', models.CharField(max_length=50)),
                ('sks', models.IntegerField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('kd_soal', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kd_ampu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.AmpuMatkul')),
            ],
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('kd_nilai', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nilai', models.IntegerField(max_length=3)),
                ('index', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kd_soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.DetailSoal')),
            ],
        ),
        migrations.AddField(
            model_name='detailsoal',
            name='kd_soal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Soal'),
        ),
        migrations.AddField(
            model_name='ampumatkul',
            name='kd_kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Kelas'),
        ),
        migrations.AddField(
            model_name='ampumatkul',
            name='kd_mk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.MataKuliah'),
        ),
        migrations.AddField(
            model_name='ampumatkul',
            name='nip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Dosen'),
        ),
    ]
