# Generated by Django 3.0 on 2020-03-10 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampumatkul',
            name='semester',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='detailsoal',
            name='bobot',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='matakuliah',
            name='sks',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='nilai',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
