# Generated by Django 3.0 on 2020-03-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20200310_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ampumatkul',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='id',
        ),
        migrations.RemoveField(
            model_name='kelas',
            name='id',
        ),
        migrations.RemoveField(
            model_name='matakuliah',
            name='id',
        ),
        migrations.AlterField(
            model_name='ampumatkul',
            name='kd_ampu',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nip',
            field=models.CharField(max_length=18, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='kd_kelas',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matakuliah',
            name='kd_mk',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
