# Generated by Django 3.0 on 2020-03-10 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20200310_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('nim', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('jurusan', models.CharField(max_length=50)),
                ('prodi', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kd_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Kelas')),
            ],
        ),
        migrations.AddField(
            model_name='nilai',
            name='nim',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='apps.Mahasiswa'),
            preserve_default=False,
        ),
    ]
