# Generated by Django 3.0 on 2020-03-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
