# Generated by Django 3.0 on 2020-03-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20200320_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kelas',
            old_name='created_at',
            new_name='created_att',
        ),
    ]
