# Generated by Django 3.0 on 2020-03-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20200320_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kelas',
            old_name='created_att',
            new_name='created_at',
        ),
    ]
