# Generated by Django 3.0 on 2020-03-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20200320_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='created_at',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='updated_at',
            field=models.CharField(max_length=20),
        ),
    ]
