# Generated by Django 3.0 on 2020-03-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_auto_20200320_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
