# Generated by Django 3.0 on 2020-03-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_auto_20200320_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampumatkul',
            name='created_at',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ampumatkul',
            name='updated_at',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='detailsoal',
            name='created_at',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='detailsoal',
            name='updated_at',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='created_at',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='updated_at',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='created_at',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='created_at',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='updated_at',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='matakuliah',
            name='created_at',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='matakuliah',
            name='updated_at',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='created_at',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='updated_at',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='soal',
            name='created_at',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='soal',
            name='updated_at',
            field=models.CharField(max_length=20),
        ),
    ]
