# Generated by Django 3.0 on 2020-03-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_auto_20200320_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='kelas',
            field=models.CharField(max_length=60),
        ),
    ]
