# Generated by Django 3.0 on 2020-03-23 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_auto_20200320_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='kd_kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.Kelas'),
        ),
    ]
