# Generated by Django 3.0 on 2020-03-23 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_auto_20200323_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampumatkul',
            name='kd_kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.Kelas'),
        ),
        migrations.AlterField(
            model_name='ampumatkul',
            name='kd_mk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.MataKuliah'),
        ),
        migrations.AlterField(
            model_name='ampumatkul',
            name='nip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.Dosen'),
        ),
        migrations.AlterField(
            model_name='detailsoal',
            name='kd_soal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.Soal'),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='kd_soal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.DetailSoal'),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='nim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.Mahasiswa'),
        ),
        migrations.AlterField(
            model_name='soal',
            name='kd_ampu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.AmpuMatkul'),
        ),
    ]
