# Generated by Django 3.0 on 2020-03-23 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_auto_20200323_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilai',
            name='kd_soal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.Soal'),
        ),
    ]
