# Generated by Django 3.0 on 2020-03-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_auto_20200323_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ampumatkul',
            name='kd_kelas',
        ),
        migrations.RemoveField(
            model_name='ampumatkul',
            name='kd_mk',
        ),
    ]
