# Generated by Django 3.0 on 2020-03-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_auto_20200323_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ampumatkul',
            name='nip',
        ),
        migrations.AddField(
            model_name='ampumatkul',
            name='nipnya',
            field=models.ManyToManyField(to='apps.Dosen'),
        ),
        migrations.AlterField(
            model_name='ampumatkul',
            name='kd_ampu',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
