# Generated by Django 3.0 on 2020-03-23 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_auto_20200323_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ampumatkul',
            name='nipnya',
        ),
        migrations.AddField(
            model_name='ampumatkul',
            name='nip',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='apps.Dosen'),
            preserve_default=False,
        ),
    ]
