# Generated by Django 3.0 on 2020-03-23 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_auto_20200323_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='ampumatkul',
            name='kd_kelas',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='apps.Kelas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ampumatkul',
            name='kd_mk',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='apps.MataKuliah'),
            preserve_default=False,
        ),
    ]
