# Generated by Django 3.0 on 2020-07-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_auto_20200323_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailsoal',
            old_name='jawaban',
            new_name='jawaban1',
        ),
        migrations.RemoveField(
            model_name='detailsoal',
            name='bobot',
        ),
        migrations.AddField(
            model_name='detailsoal',
            name='jawaban2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailsoal',
            name='jawaban3',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
